# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# JF: still considering Travis deploy.  Automated tests, especially for PR's are worth it, but
#     pypi deploy is simple, scripted with a task, and only needs to be done when new versions are tagged.
#     Automating this seems like over-complicating things - more error-prone than helpful?
# Run the following command to finish PyPI deployment setup:
# $ travis login --pro --github-token ghp_xxxx;  travis encrypt --pro --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: powderflask
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: powderflask/django_fmft
    python: 3.9
